# Assigment 3 (pandas)

In [1]:
import pandas as pd

**1. Refer to googleplaystore.csv file and solve following questions**

In [2]:
data = pd.read_csv("dataset/googleplaystore.csv")

**a. Display First 5 records from Dataframe.**

In [3]:
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

**b. Display category with highest number of apps registered.**

In [96]:
data['Category'].value_counts().head(2)

Category
FAMILY    1972
GAME      1144
Name: count, dtype: int64

**c. What is the average rating for all the apps**

In [11]:
data['Rating'].mean()

np.float64(4.193338315362443)

**d. Display total number of apps which even supports Andriod version 2.3 and up**

In [29]:
data[data['Android Ver']== '2.3 and up'].value_counts()

App                                 Category   Rating  Reviews  Size                Installs      Type  Price  Content Rating  Genres                     Last Updated       Current Ver         Android Ver
Elmo Calls by Sesame Street         FAMILY     3.9     6903     25M                 1,000,000+    Free  0      Everyone        Educational;Pretend Play   January 31, 2018   2.0.7               2.3 and up     3
Scarf Fashion Designer              LIFESTYLE  4.4     16637    10M                 1,000,000+    Free  0      Everyone        Lifestyle                  June 18, 2017      1.8                 2.3 and up     2
Block Puzzle                        GAME       4.6     59907    7.8M                5,000,000+    Free  0      Everyone        Puzzle                     March 6, 2018      2.9                 2.3 and up     2
slither.io                          GAME       4.4     5235294  Varies with device  100,000,000+  Free  0      Everyone        Action                     November 14, 2017  Varies with device  2.3 and up     2
Strawberry Shortcake BerryRush      FAMILY     4.3     525552   48M                 10,000,000+   Free  0      Everyone        Action;Action & Adventure  October 15, 2017   1.2.3               2.3 and up     2
                                                                                                                                                                                                               ..
SCM FPS Status                      BUSINESS   4.2     123      3.3M                10,000+       Free  0      Everyone        Business                   April 28, 2018     3.5                 2.3 and up     1
Modern Counter Terrorist FPS Shoot  GAME       4.0     795      41M                 100,000+      Free  0      Teen            Action                     August 29, 2017    1.2                 2.3 and up     1
Monster Ride Pro                    GAME       5.0     1        24M                 10+           Free  0      Everyone        Racing                     March 5, 2018      2.0                 2.3 and up     1
sugar, sugar                        FAMILY     4.2     1405     9.5M                10,000+       Paid  $1.20  Everyone        Puzzle                     June 5, 2018       2.7                 2.3 and up     1
Poker Pro.Fr                        GAME       4.2     5442     17M                 100,000+      Free  0      Teen            Card                       May 22, 2018       4.1.3               2.3 and up     1
Name: count, Length: 573, dtype: int64

In [30]:
(data['Android Ver']== '2.3 and up').sum()

np.int64(652)

**e. Impute the missing values available in rating column with respective measure
of central tendency.**

In [39]:
data['Rating'].isna().sum()

np.int64(1474)

In [53]:
data['Rating'].mean()

np.float64(4.193338315362443)

In [63]:
data.loc[data['Rating'].isna()==True,'Rating'] = 4.19
data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.10,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.90,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.70,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.50,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.30,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.50,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.00,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,4.19,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.50,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.50,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [64]:
data['Rating'].isna().sum()

np.int64(0)

**2. Refer to salaries.xlsx file and solve following questions**

In [72]:
df = pd.read_excel("dataset/Salaries.xlsx")

**a. Check head of the dataframe**

In [73]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

**b. Find out details about no. of entries & no. of columns in the data frame**

In [74]:
df.shape

(1000, 13)

**c. What is the average base pay?**

In [75]:
df['BasePay'].mean()

np.float64(145663.9982)

**d. What is the highest amount of overtime pay in the dataset?**

In [77]:
df['OvertimePay'].max()

np.float64(245131.88)

**e. What is the job title of JOSEPH DRISCOLL?**

In [79]:
df[df['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

**f. How much does JOSEPH DRISCOLL make (including benefits)?**

In [84]:
df[df['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

**g. How many unique job titles are there?**

In [87]:
df['JobTitle'].nunique()

113

**h. What are the top 5 common jobs?**

In [93]:
df['JobTitle'].value_counts().head()

JobTitle
FIREFIGHTER                           133
LIEUTENANT, FIRE DEPARTMENT            62
FIRE FIGHTER PARAMEDIC                 43
CAPTAIN, FIRE SUPPRESSION              42
BATTALION CHIEF, (FIRE DEPARTMENT)     41
Name: count, dtype: int64